steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--unsafe-perms']
  dir: 'functions/addPlayer'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'compile']
  dir: 'functions/addPlayer'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'get-player-info'
    - '--trigger-http'
    - '--runtime'
    - 'nodejs10'
    - '--entry-point'
    - 'addPlayer'
    - '--set-env-vars'
    - 'MONGO_URL=${_MONGO_URL}'
  dir: 'functions/addPlayer/lib'

timeout: 1200s